name: Python311
channels:
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - pip:
      - -i https://mirrors.ustc.edu.cn/pypi/simple
      - requests~=2.32.2
      - pyyaml~=6.0.1
      - yapf~=0.40.2